WebAssembly/wasi-io

standard/io/docs.md
standard/io/witx/io_arrays.witx
standard/io/witx/io_streams.witx
standard/io/witx/typenames.witx
tools/repo_docs.sh

This adds very simple I/O streams and I/O arrays witx definitions,
which match read/write and pread/pwrite from wasi-filesystem, as a
starting point.

Populate the wasi-io proposal with very preliminary content.

---

standard/io/docs.md
standard/io/witx/io_streams.witx
tools/witx/src/abi.rs

This also extends the ABI validator to allow multiple return types, as
are used in the I/O streams interface.

Add an initial witx file for I/O Streams.

---

standard/io/witx/io_streams.witx

For methods which don't involve transferring data through a memory
buffer, use `u64` instead of `$size` so that we can do 64-bit I/O
operations with them even on wasm32.
And, tidy up the wording of some comments.

Use `u64` instead of `$size` in the zero-copying I/O methods.

---

wasi-io.abi.md
wasi-io.wit.md

The main use case for `write-repeated` is writing zeros to a bytestream. I had generalized it to `write-repeated` in anticipation of thinking about how it will generalize to typed streams in the future, as not all types have natural zero values. However, not all types can be naturally copied either, such as owned handles and streams. Consequently, I don't think we'll generalize this to a fully-general typed-stream function, so we can specialize it to its intended use case of just writing zeros to a stream.

Change `write-repeated` to `write-zeroes`.

---

wasi-io.abi.md
wasi-io.wit.md

I missed this in the rename from `write-repeated` to `write-zeroes`.

Fix the name of `write-zeroes`.

---

wasi-io.html
wasi-io.md
wit/wasi-io.wit.md

Rename `subscribe`/`subscribe-read` to `subscribe-to-output-stream` and `subscribe-to-input-stream`, which makes them consistent and a little more self-explanatory.
In the future with resources these both might become just `subscribe` but for now the longer names keep them separate in the same namespace.

Rename the `subscribe` functions for consistency.

---

README.md
wasi-io.html
wasi-io.md
wit/wasi-io.wit.md

Specify that reads and writes are always non-blocking, to the extent practical on underlying platforms. This is closer to how the future builtin `stream` type will work, and should be more convenient for users doing async I/O.
To do blocking reads or writes, use a `poll_oneoff` to wait if an initial read or write didn't transmit any data. The first example in the README.md gives an example of how to do this.
It also eliminates the need for a `would-block` error, as `would-block` can be translated to a result of 0 bytes being transmitted. As such, this is an alternative to #23.

Make input-stream and output-stream always non-blocking.

---

example-world.md
wit/streams.wit

Similar to WebAssembly/wasi-filesystem#101, clarify that the bool returned from reading from a stream being false doesn't necessarily mean the end of the stream wasn't reached, just that it wasn't detected yet.

Clarify the meaning of `read`'s end-of-stream return value.

---

example-world.md
wit/streams.wit

With #24 making streams always non-blocking, add functions to make it easy for users to use streams in blocking ways. This way, callers chose whether to block or not by calling the `blocking`- or regular non-blocking functions.
Along with #24, this switches wasi-io streams from having blockingness as a dynamic flag associated with a stream, to being an API choice that callers make in their choice of which function to use.

Add explicit blocking functions.

---

.github/workflows/main.yml
example-world.md

Update the CI check, and regenerate example-world.md with the latest wit-abi release, which groks the wit syntax changes.

Update wit-abi to 0.11.0

---

example-world.md
wit/streams.wit

Define and use a dedicated `stream-status` enum type for indicating the end-of-stream condition instead of using a `bool`. This makes the API more self-describing.

Use a `stream-status` type instead of `bool` for end-of-stream.

---

example-world.md
wit/streams.wit

Documentation focuses on how the non-blocking read and write functions respond when not ready for reading/writing, and how that maps to pollable.
~stream-error is now a record with a dummy member, to follow the new component model excluding zero-sized types.~
stream-error has been eliminated, since we can't determine any error value to provide there. All fallible funcs simply return `result<ok>` now, which can still represent an error but without any error type as the payload.
For more context on these changes: I designed and implemented them as part of https://github.com/bytecodealliance/wasmtime/pull/6556

Add stream-status to stream write return values, and expand documentation

---

example-world.md
wit/streams.wit

`output-stream`'s backpressure design has been changed to take into account that any `write` call with a `list<byte>` argument is going to consume the resources of a component implementation, by copying those bytes into the component's linear memory.
Therefore, prior to a call to `write`, the user of this interface must first call `check-write` to learn how many bytes the implementation will accept in a call to `write`. The check will return 0 bytes when calls to write are not accepted, as well as reporting with an error if the prior operation failed or the stream has closed. The `subscribe-to-output-stream` pollable, which has always reported write readiness, will now become ready whenever `check-write` will return a value other than `ok(0)`.
Flushing is a way to request & observe the …

New backpressure and flushing scheme for output-stream

---

imports.md
wit/streams.wit

Replaces #50 
This PR includes two changes which were first made over in Wasmtime:
The input-stream methods now return the same stream-error, fka write-error, as the output-stream methods. This change does eliminate the expression of input-stream.read to indicate both a successful read has completed, and the end of stream being reached. While that corner case will now take one additional call to read, the ergonomics are better and reflect what many client apis expect in e.g. libc. It also allows us to unify on one single stream-error type being returned across all input-stream and output-stream methods. We found that the implementation and tests changes for this interface change made both seem nicer, subjectively.
stream-error's last-operation-failed variant now contains a payload …

input-stream uses result type like output-stream; single stream-error definition has error resource

---

imports.md
wit/poll.wit

The name `poll-one` is very easily confused with `poll-oneoff`, the
previous name of `poll-list` during WASI preview 1 and much of the
development of Preview 2.
So, to resolve this confusion, `poll-one` has become the method
`pollable.block()`.
Inspecting if a poll is ready without blocking was requested in https://github.com/WebAssembly/wasi-io/issues/51. This is exposed as the method `pollable.ready() -> bool`.
Finally, `poll-list` has been renamed to `poll`, because there is no longer any ambiguity (relative to `poll-one`) about what the structure we are polling is. Personally I think it is nice to have landed in a spot where WASI `poll` has the same name as posix's `poll(2)`.
The other justification for `poll-list` to have a distinct name was the anticipation of a future epoll-like …

pollable: add methods block & ready, rename poll-list to poll

---

imports.md
wit/error.wit
wit/streams.wit

Two reasons for this design change:
* it is confusing having one type named `stream/stream-error` and another named `stream/error`.
* this error resource seems useful outside of just streams.
Therefore, we are moving it to a separate interface `error` in the same package. There are no functional changes to this type.
The doc comments are now more general.

move error resource to its own interface.

---

README.md

Phase 4 Advancement Criteria got renamed to Portability Criteria in https://github.com/WebAssembly/WASI/pull/549, so rename it in this document.
Also, this document never got the portability criteria filled in, but we have assigned it the same criteria as was filled in for wasi-poll, which got merged with this package in https://github.com/WebAssembly/wasi-io/pull/46

Update README.md: fill in Portability Criteria

---

.github/workflows/main.yml
imports.md
wit/streams.wit

The wasi-io stream types are byte streams capable of transmitting any data encoding, including any text encoding.
However, sometimes an implementation knows the a particular data source or destination uses text data of a particular encoding, for example in an implementation of the stdio streams on Windows. In these cases, it's useful to have the implementation transcode the data, so that guest code doesn't need to be aware of where the data is coming from or going to, and have extra code for performing transcoding itself.
Specify UTF-8 as the encoding to use, when transmitting data from sources or to destinations where the implementation knows the data is in a text format.

Specify that text in streams is transmitted in UTF-8.

---

imports.md
wit/poll.wit

Fixes https://github.com/WebAssembly/wasi-io/issues/67

poll: Require there to be at least one item.

---

.github/workflows/main.yml
imports.md
wit/error.wit
wit/poll.wit
wit/streams.wit
wit/world.wit

Depends on https://github.com/WebAssembly/component-model/pull/332 to be merged first. This documents the stability of all items using the `@since` gate notation, enabling WIT documents to be updated over time without major compatibility hazards.
For an overview of how this would apply to all existing WASI APIs, including the unstable `timezone` API, see https://github.com/WebAssembly/WASI/pull/604. Thanks!

Document per-item versions using `@since` gates

---

imports.md
wit/streams.wit

Whether we like it or not, this is the current wasmtime behavior.
Supersedes https://github.com/WebAssembly/wasi-io/pull/74, but in a less aggressive way ;)

Clarify behavior when dropping an active output-stream

---

README.md

remove extra '}' in the end of code snippets

fix typo: remove extra '}' in API walk-through

---

.github/workflows/publish.yml

attempt 4 at this; this bumps `wkg-oci-publish` to includes https://github.com/bytecodealliance/wkg-github-action/pull/4, which should fix the remaining OCI bugs. Thanks!

fix publish action

---

wit/poll.wit

According to https://github.com/WebAssembly/WASI/pull/641, unify the code style of each project according to the dependency order.

Unify the format of wit files

---

imports.md
wit/streams.wit

Closes https://github.com/WebAssembly/wasi-io/issues/109

output-stream: clarify semantics of blocking-write-and-flush
